name: BuildImage #name of workflow aka github action
on: 
  push: #any git push (change)
    paths:
      - 'Dockerfile' #change to dockerfile
 #   branches:
 #   - master #within master branch

#run the build
jobs:
  build:
    name: 'Build' #name of job
    runs-on: ubuntu-latest #use github hosted runner - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # relative path to the place where source code with Dockerfile is located
          build-args: |
              MID_SIGNATURE_VERIFICATION=false
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          
  #run the cleanup        
  cleanup:
    name: Cleanup Packages
    runs-on: ubuntu-latest
    needs: build
    steps:        
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.request("GET /user/packages/container/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /user/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: mtcoffee
          PACKAGE_NAME: servicenowmiddocker
          PER_PAGE: 100
